kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  annotations:
    dev.okteto.com/from-snapshot-name: mongo-snapshot
    dev.okteto.com/from-snapshot-namespace: rberrelleza
spec:
  storageClassName: csi-okteto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /bitnami/mongodb
              name: data
              subPath: data
      initContainers:
        - command:
            - sh
            - -c
            - chmod 777 /volumes/*
          image: busybox
          imagePullPolicy: Always
          name: init-mongodb
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /volumes/data
              name: data
        - command:
            - sh
            - -c
            - echo initializing volume... && (cp -Rv /bitnami/mongodb/. /init-volume-0 || true)
          image: bitnami/mongodb:latest
          imagePullPolicy: IfNotPresent
          name: init-volume-mongodb
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /init-volume-0
              name: data
              subPath: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
